services:
  springboot:
    build: .
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - DB_URL=test-url
      - spring.jvm.args=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
    depends_on:
      - 'postgres'
  postgres:
    image: 'postgres:18-alpine3.22'
    environment:
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
