services:
  springboot:
    build: .
    ports:
      - '8080:8080'
      - '5005:5005'
    environment:
      - DB_URL=test-url
      - MAVEN_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
#    depends_on:
#      - 'postgres'
#  postgres:
#    image: 'postgres:latest'
#    environment:
#      - 'POSTGRES_DB=mydatabase'
#      - 'POSTGRES_PASSWORD=secret'
#      - 'POSTGRES_USER=myuser'
#    ports:
#      - '5432'
